language: java

# test with java 9 support
jdk: openjdk11

# using the right gradle version
before_install: 
  - gradle -b wrapper.gradle wrapper
  - gradle -v

# list dependencies in the install step.
# this forces the check that all dependencies are available
install: gradle dependencies

# run unit tests in main script
script: gradle test
